/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import employees.*;
import login.LoginManager;
import javax.swing.*;

/**
 * GUI for adding a new employee to the system
 * @author Adrian Zielinski
 */
public class AddEmployeeGUI extends javax.swing.JFrame {
    
    private Database database;
    private AdminMenuGUI adminMenuGUI;
    
    /**
     * Creates new form AddEmployeeGUI with database and parent frame
     * @param database the database instance
     * @param parentFrame the parent frame
     */
    public AddEmployeeGUI(Database database, AdminMenuGUI adminMenuGUI) {
        initComponents();
        setLocationRelativeTo(adminMenuGUI);
        
        this.database = database;
        this.adminMenuGUI = adminMenuGUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        jobTitleComboBox = new javax.swing.JComboBox<>();
        jobTitleLbl = new javax.swing.JLabel();
        phoneNumberTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        addEmployeeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");

        firstNameTxt.setText("First Name");

        lastNameTxt.setText("Last Name");

        jobTitleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Driver" }));

        jobTitleLbl.setText("Job Title");

        phoneNumberTxt.setText("Phone Number");

        salaryTxt.setText("Salary");

        addEmployeeButton.setText("Add");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jobTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstNameTxt)
                    .addComponent(phoneNumberTxt)
                    .addComponent(lastNameTxt)
                    .addComponent(jobTitleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salaryTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(addEmployeeButton)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobTitleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobTitleLbl))
                .addGap(18, 18, 18)
                .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addEmployeeButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * adds a new employee based on the form data
     */
    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        // get form data
        String firstName = firstNameTxt.getText().trim();
        String lastName = lastNameTxt.getText().trim();
        String jobTitle = (String) jobTitleComboBox.getSelectedItem();
        String phoneNumber = phoneNumberTxt.getText().trim();
        float salary = Float.parseFloat(salaryTxt.getText().trim());

        // get employee management and login manager from database
        EmployeeManagement employeeManagement = database.getEmployeeManagement();
        LoginManager loginManager = database.getLoginManager();

        // create employee based on job title
        if (jobTitle.equals("Admin")) {
            new Admin(firstName, lastName, jobTitle, phoneNumber, salary, employeeManagement, loginManager);
        } else if (jobTitle.equals("Driver")) {
            new Driver(firstName, lastName, jobTitle, phoneNumber, salary, employeeManagement, loginManager);
        }

        // show success message
        JOptionPane.showMessageDialog(this,
                "Employee added successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        // refresh employee table in parent frame if available
        if (adminMenuGUI != null) {
            adminMenuGUI.populateEmployeeTable();
        }

        // close the form
        this.dispose();
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JComboBox<String> jobTitleComboBox;
    private javax.swing.JLabel jobTitleLbl;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JTextField salaryTxt;
    // End of variables declaration//GEN-END:variables
}
