/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import employees.*;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import login.LoginManager;
import javax.swing.*;

/**
 * GUI for adding a new employee to the system
 * @author Adrian Zielinski
 */
public class AddEmployeeGUI extends javax.swing.JFrame {
    
    private Database database;
    private AdminMenuGUI adminMenuGUI;
    
    /**
     * Creates new form AddEmployeeGUI with database and parent frame
     * @param database the database instance
     * @param parentFrame the parent frame
     */
    public AddEmployeeGUI(Database database, AdminMenuGUI adminMenuGUI) {
        initComponents();
        setLocationRelativeTo(adminMenuGUI);
        
        // initialize instance variables
        this.database = database;
        this.adminMenuGUI = adminMenuGUI;
        
        // style components
        styleComboBox(jobTitleComboBox);
        styleButton(addEmployeeButton);      
        applyTextFieldEffects(firstNameTxt, "First Name");
        applyTextFieldEffects(lastNameTxt, "Last Name");
        applyTextFieldEffects(phoneNumberTxt, "Phone Number");
        applyTextFieldEffects(salaryTxt, "Phone Number");      
        jobTitleLbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        jobTitleComboBox = new javax.swing.JComboBox<>();
        phoneNumberTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        addEmployeeButton = new javax.swing.JButton();
        jobTitleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");

        jPanel1.setBackground(new java.awt.Color(215, 224, 223));

        firstNameTxt.setForeground(new java.awt.Color(153, 153, 153));
        firstNameTxt.setText("First Name");

        lastNameTxt.setForeground(new java.awt.Color(153, 153, 153));
        lastNameTxt.setText("Last Name");

        jobTitleComboBox.setForeground(new java.awt.Color(153, 153, 153));
        jobTitleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Driver" }));

        phoneNumberTxt.setForeground(new java.awt.Color(153, 153, 153));
        phoneNumberTxt.setText("Phone Number");

        salaryTxt.setForeground(new java.awt.Color(153, 153, 153));
        salaryTxt.setText("Salary");

        addEmployeeButton.setText("Add");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        jobTitleLbl.setText("Job Title");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jobTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salaryTxt)
                    .addComponent(phoneNumberTxt)
                    .addComponent(firstNameTxt)
                    .addComponent(lastNameTxt)
                    .addComponent(jobTitleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobTitleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobTitleLbl))
                .addGap(16, 16, 16)
                .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * adds a new employee based on the form data
     */
    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        // get form data
        String firstName = firstNameTxt.getText().trim();
        String lastName = lastNameTxt.getText().trim();
        String jobTitle = (String) jobTitleComboBox.getSelectedItem();
        String phoneNumber = phoneNumberTxt.getText().trim();
        float salary = Float.parseFloat(salaryTxt.getText().trim());

        // get employee management and login manager from database
        EmployeeManagement employeeManagement = database.getEmployeeManagement();
        LoginManager loginManager = database.getLoginManager();

        // create employee based on job title
        if (jobTitle.equals("Admin")) {
            new Admin(firstName, lastName, jobTitle, phoneNumber, salary, employeeManagement, loginManager);
        } else if (jobTitle.equals("Driver")) {
            new Driver(firstName, lastName, jobTitle, phoneNumber, salary, employeeManagement, loginManager);
        }

        // show success message
        JOptionPane.showMessageDialog(this,
                "Employee added successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        // refresh employee table in parent frame if available
        if (adminMenuGUI != null) {
            adminMenuGUI.populateEmployeeTable();
        }

        // close the form
        this.dispose();
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    /**
     * styles the combo box
     * @param comboBox 
     */
    private void styleComboBox(JComboBox<?> comboBox) {
    comboBox.setBackground(Color.WHITE);
    comboBox.setForeground(Color.BLACK);
    comboBox.setFont(new Font("Segoe UI", Font.PLAIN, 12));
    comboBox.setPreferredSize(new Dimension(160, 23));
    comboBox.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    comboBox.setBorder(BorderFactory.createLineBorder(Color.WHITE));

    comboBox.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            comboBox.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        }

        @Override
        public void focusLost(FocusEvent e) {
            comboBox.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        }
    });
    }
    
    /**
     * styles the buttons
     * @param button 
     */
    private void styleButton(JButton button) {
        button.setBackground(Color.WHITE);
        button.setForeground(Color.BLACK);
        button.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        button.setPreferredSize(new Dimension(160, 23));
        button.setOpaque(true);
        button.setBorderPainted(false);
        button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Color hover = Color.green;

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(hover);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(Color.WHITE);
            }
        });
    }
    
    /**
     * styles the text fields
     * @param field
     * @param placeholder 
     */
    private void applyTextFieldEffects(JTextField field, String placeholder) {
        field.setForeground(Color.GRAY);
        field.setText(placeholder);
        field.setBorder(BorderFactory.createLineBorder(Color.WHITE));

        field.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
                field.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(Color.GRAY);
                }
                field.setBorder(BorderFactory.createLineBorder(Color.WHITE));
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jobTitleComboBox;
    private javax.swing.JLabel jobTitleLbl;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JTextField salaryTxt;
    // End of variables declaration//GEN-END:variables
}
