/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * GUI for adding a new route
 * @author Adrian Zielinski
 */
public class AddRouteGUI extends javax.swing.JFrame {
    
    private Database database;
    private AdminMenuGUI adminMenuGUI;
    private DefaultListModel<String> stopsListModel;
    private ArrayList<BusStop> busStops;
    
    /**
     * Creates new form AddRouteGUI
     * @param database the database
     * @param adminMenuGUI the parent AdminMenuGUI
     */
    public AddRouteGUI(Database database, AdminMenuGUI adminMenuGUI) {
        this.database = database;
        this.adminMenuGUI = adminMenuGUI;
        this.busStops = new ArrayList<>();
        initComponents();
        
        // initialize the list model for bus stops
        stopsListModel = new DefaultListModel<>();
        stopsList.setModel(stopsListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRoutePanel = new javax.swing.JPanel();
        routeNameLabel = new javax.swing.JLabel();
        routeNameTxt = new javax.swing.JTextField();
        stopsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stopsList = new javax.swing.JList<>();
        addStopButton = new javax.swing.JButton();
        removeStopButton = new javax.swing.JButton();
        addRouteButton = new javax.swing.JButton();
        stopNameLabel = new javax.swing.JLabel();
        stopNameTxt = new javax.swing.JTextField();
        distanceLabel = new javax.swing.JLabel();
        distanceTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a New Route");

        addRoutePanel.setBackground(new java.awt.Color(215, 224, 223));

        routeNameLabel.setText("Route Name:");

        stopsLabel.setText("Bus Stops:");

        jScrollPane1.setViewportView(stopsList);

        addStopButton.setText("Add Stop");
        addStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStopButtonActionPerformed(evt);
            }
        });

        removeStopButton.setText("Remove Stop");
        removeStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStopButtonActionPerformed(evt);
            }
        });

        addRouteButton.setText("Add Route");
        addRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteButtonActionPerformed(evt);
            }
        });

        stopNameLabel.setText("Stop Name:");

        distanceLabel.setText("Distance to Next Stop (miles):");

        javax.swing.GroupLayout addRoutePanelLayout = new javax.swing.GroupLayout(addRoutePanel);
        addRoutePanel.setLayout(addRoutePanelLayout);
        addRoutePanelLayout.setHorizontalGroup(
            addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoutePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRoutePanelLayout.createSequentialGroup()
                        .addComponent(routeNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(routeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRoutePanelLayout.createSequentialGroup()
                        .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopsLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stopNameLabel)
                            .addComponent(stopNameTxt)
                            .addComponent(distanceLabel)
                            .addComponent(distanceTxt)
                            .addComponent(addStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRoutePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        addRoutePanelLayout.setVerticalGroup(
            addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoutePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeNameLabel)
                    .addComponent(routeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopsLabel)
                    .addComponent(stopNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addRoutePanelLayout.createSequentialGroup()
                        .addComponent(stopNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(distanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addStopButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeStopButton))
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30)
                .addComponent(addRouteButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRoutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRoutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStopButtonActionPerformed
        String stopName = stopNameTxt.getText().trim();
        String distanceStr = distanceTxt.getText().trim();
       
        double distance = Double.parseDouble(distanceStr);

        // create and add the bus stop
        BusStop busStop = new BusStop(stopName, distance);
        busStops.add(busStop);

        // add to the list model
        stopsListModel.addElement(stopName + " (Distance: " + distance + " miles)");

        // clear the input fields
        stopNameTxt.setText("");
        distanceTxt.setText("");
    }//GEN-LAST:event_addStopButtonActionPerformed

    private void removeStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStopButtonActionPerformed
        int selectedIndex = stopsList.getSelectedIndex();
        
        if (selectedIndex >= 0) {
            // remove from the list model and the bus stops list
            stopsListModel.remove(selectedIndex);
            busStops.remove(selectedIndex);
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Please select a stop to remove.", 
                    "No Stop Selected", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeStopButtonActionPerformed

    private void addRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteButtonActionPerformed
        String routeName = routeNameTxt.getText().trim();
        
        if (routeName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a route name.", 
                    "Missing Information", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // create a new route
        Route newRoute = new Route(routeName, database.getRouteManager());
        
        // add all bus stops to the route
        for (BusStop stop : busStops) {
            newRoute.addStop(stop);
        }
        
        // refresh the route table in AdminMenuGUI
        if (adminMenuGUI != null) {
            adminMenuGUI.populateRouteTable();
        }
        
        JOptionPane.showMessageDialog(this, 
                "Route added successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
        
        this.dispose();
    }//GEN-LAST:event_addRouteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new AddRouteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRouteButton;
    private javax.swing.JPanel addRoutePanel;
    private javax.swing.JButton addStopButton;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JTextField distanceTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeStopButton;
    private javax.swing.JLabel routeNameLabel;
    private javax.swing.JTextField routeNameTxt;
    private javax.swing.JLabel stopNameLabel;
    private javax.swing.JTextField stopNameTxt;
    private javax.swing.JLabel stopsLabel;
    private javax.swing.JList<String> stopsList;
    // End of variables declaration//GEN-END:variables
}
