/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * GUI for adding a new route
 * @author Adrian Zielinski
 */
public class AddRouteGUI extends javax.swing.JFrame {
    
    private Database database;
    private AdminMenuGUI adminMenuGUI;
    private DefaultListModel<String> stopsListModel;
    private ArrayList<BusStop> busStops;
    
    /**
     * Creates new form AddRouteGUI
     * @param database the database
     * @param adminMenuGUI the parent AdminMenuGUI
     */
    public AddRouteGUI(Database database, AdminMenuGUI adminMenuGUI) {
        this.database = database;
        this.adminMenuGUI = adminMenuGUI;
        this.busStops = new ArrayList<>();
        initComponents();
        
        // initialize the list model for bus stops
        stopsListModel = new DefaultListModel<>();
        stopsList.setModel(stopsListModel);
        
        applyTextFieldEffects(routeNameTxt, "Route Name");
        applyTextFieldEffects(stopNameTxt, "Stop Name");
        applyTextFieldEffects(distanceTxt, "Distance to Next Stop (miles)");

        styleButton(addStopButton);
        styleButton(removeStopButton);
        styleButton(addRouteButton);
        
        stopsLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRoutePanel = new javax.swing.JPanel();
        routeNameTxt = new javax.swing.JTextField();
        stopsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stopsList = new javax.swing.JList<>();
        addStopButton = new javax.swing.JButton();
        removeStopButton = new javax.swing.JButton();
        addRouteButton = new javax.swing.JButton();
        stopNameTxt = new javax.swing.JTextField();
        distanceTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a New Route");

        addRoutePanel.setBackground(new java.awt.Color(215, 224, 223));

        routeNameTxt.setForeground(new java.awt.Color(153, 153, 153));
        routeNameTxt.setText("Route Name");

        stopsLabel.setText("Bus Stops:");

        jScrollPane1.setViewportView(stopsList);

        addStopButton.setText("Add Stop");
        addStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStopButtonActionPerformed(evt);
            }
        });

        removeStopButton.setText("Remove Stop");
        removeStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStopButtonActionPerformed(evt);
            }
        });

        addRouteButton.setText("Add Route");
        addRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteButtonActionPerformed(evt);
            }
        });

        stopNameTxt.setForeground(new java.awt.Color(153, 153, 153));
        stopNameTxt.setText("Stop Name");

        distanceTxt.setForeground(new java.awt.Color(153, 153, 153));
        distanceTxt.setText("Distance to Next Stop (miles)");

        javax.swing.GroupLayout addRoutePanelLayout = new javax.swing.GroupLayout(addRoutePanel);
        addRoutePanel.setLayout(addRoutePanelLayout);
        addRoutePanelLayout.setHorizontalGroup(
            addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoutePanelLayout.createSequentialGroup()
                .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRoutePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(stopsLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRoutePanelLayout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stopNameTxt)
                    .addComponent(distanceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(addStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(routeNameTxt)
                    .addComponent(addRouteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        addRoutePanelLayout.setVerticalGroup(
            addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoutePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(stopsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addRoutePanelLayout.createSequentialGroup()
                        .addComponent(routeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stopNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(distanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addStopButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeStopButton)
                        .addGap(18, 18, 18)
                        .addComponent(addRouteButton))
                    .addComponent(jScrollPane1))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRoutePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRoutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Adds a new bus stop when the Add Stop button is clicked
     * @param evt 
     */
    private void addStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStopButtonActionPerformed
        String stopName = stopNameTxt.getText().trim();
        String distanceStr = distanceTxt.getText().trim();
       
        double distance = Double.parseDouble(distanceStr);

        // create and add the bus stop
        BusStop busStop = new BusStop(stopName, distance);
        busStops.add(busStop);

        // add to the list model
        stopsListModel.addElement(stopName + " (Distance: " + distance + " miles)");

        // clear the input fields
        stopNameTxt.setText("");
        distanceTxt.setText("");
    }//GEN-LAST:event_addStopButtonActionPerformed

    /**
     * Removes bus stop when the Remove Stop button is clicked
     * @param evt 
     */
    private void removeStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStopButtonActionPerformed
        int selectedIndex = stopsList.getSelectedIndex();
        
        if (selectedIndex >= 0) {
            // remove from the list model and the bus stops list
            stopsListModel.remove(selectedIndex);
            busStops.remove(selectedIndex);
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Please select a stop to remove.", 
                    "No Stop Selected", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeStopButtonActionPerformed

    /**
     * Creates a new route when the add route button is clicked
     * @param evt 
     */
    private void addRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteButtonActionPerformed
        String routeName = routeNameTxt.getText().trim();
        
        if (routeName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a route name.", 
                    "Missing Information", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // create a new route
        Route newRoute = new Route(routeName, database.getRouteManager());
        
        // add all bus stops to the route
        for (BusStop stop : busStops) {
            newRoute.addStop(stop);
        }
        
        // refresh the route table in AdminMenuGUI
        if (adminMenuGUI != null) {
            adminMenuGUI.populateRouteTable();
        }
        
        JOptionPane.showMessageDialog(this, 
                "Route added successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
        
        this.dispose();
    }//GEN-LAST:event_addRouteButtonActionPerformed

    /**
     * Adds styling to the text fields
     * @param field
     * @param placeholder 
     */
    private void applyTextFieldEffects(JTextField field, String placeholder) {
        field.setForeground(Color.GRAY);
        field.setText(placeholder);
        field.setBorder(BorderFactory.createLineBorder(Color.WHITE));

        field.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
                field.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(Color.GRAY);
                }
                field.setBorder(BorderFactory.createLineBorder(Color.WHITE));
            }
        });
    }

    /**
     * Adds hover effects to the buttons
     * @param button 
     */
    private void styleButton(JButton button) {
        button.setBackground(Color.WHITE);
        button.setForeground(Color.BLACK);
        button.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        button.setPreferredSize(new Dimension(160, 23));
        button.setOpaque(true);
        button.setBorderPainted(false);
        button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Color hover = Color.green;

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(hover);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(Color.WHITE);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRouteButton;
    private javax.swing.JPanel addRoutePanel;
    private javax.swing.JButton addStopButton;
    private javax.swing.JTextField distanceTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeStopButton;
    private javax.swing.JTextField routeNameTxt;
    private javax.swing.JTextField stopNameTxt;
    private javax.swing.JLabel stopsLabel;
    private javax.swing.JList<String> stopsList;
    // End of variables declaration//GEN-END:variables
}
