/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JTextField;

/**
 *
 * @author Owner
 */
public class AddScheduleGUI extends javax.swing.JFrame {
    
    private Database database;
    private AdminMenuGUI adminMenuGUI;
    
    public AddScheduleGUI(Database database, AdminMenuGUI adminMenuGUI) {
        this.database = database;
        this.adminMenuGUI = adminMenuGUI;
        initComponents();
        styleComponents();
        setLocationRelativeTo(adminMenuGUI);
        setAutoRequestFocus(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSchedulePanel = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        routeIdTxt = new javax.swing.JTextField();
        depotIdTxt = new javax.swing.JTextField();
        startTimeTxt = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        departureTimesTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a New Schedule");

        addSchedulePanel.setBackground(new java.awt.Color(215, 224, 223));

        nameTxt.setText("Name");
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        routeIdTxt.setText("Route ID");
        routeIdTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        depotIdTxt.setText("Depot ID");
        depotIdTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        startTimeTxt.setText("Start Time");
        startTimeTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        departureTimesTxt.setText("Departure Times");
        departureTimesTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout addSchedulePanelLayout = new javax.swing.GroupLayout(addSchedulePanel);
        addSchedulePanel.setLayout(addSchedulePanelLayout);
        addSchedulePanelLayout.setHorizontalGroup(
            addSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSchedulePanelLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(addSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameTxt)
                    .addComponent(routeIdTxt)
                    .addComponent(depotIdTxt)
                    .addComponent(startTimeTxt)
                    .addComponent(departureTimesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        addSchedulePanelLayout.setVerticalGroup(
            addSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSchedulePanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(routeIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(depotIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(departureTimesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addSchedulePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addSchedulePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * create a new schedule, and add it to the schedule manager
     * @param evt 
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String scheduleName = nameTxt.getText();
        String routeId = routeIdTxt.getText();
        int depotId = Integer.parseInt(depotIdTxt.getText());
        double startTime = Double.parseDouble(startTimeTxt.getText());
        String departureTimes = departureTimesTxt.getText();
        
        Route route = database.getRouteManager().getRouteById(routeId);
        depot.Depot depot = database.getDepotManager().findDepotById(depotId);
        Schedule schedule = new Schedule(route, depot, startTime);
        schedule.setName(scheduleName);
        
        // process departure times (comma-separated)
            String[] timeStrings = departureTimes.split(",");
            for (String timeStr : timeStrings) {
                double time = Double.parseDouble(timeStr.trim());
                schedule.getDepartureTimes().add(time);
            }
        
        database.getScheduleManager().addSchedule(schedule);
        
        // refresh the schedule table in AdminMenuGUI
        if (adminMenuGUI != null) {
            adminMenuGUI.populateScheduleTable();
        }
        
        this.dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    private void addPlaceholderBehavior(JTextField field, String placeholder) {
    field.setText(placeholder);
    field.setForeground(Color.GRAY);

    field.addFocusListener(new FocusAdapter() {
        public void focusGained(FocusEvent e) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(Color.BLACK);
            }
            field.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));
        }

        public void focusLost(FocusEvent e) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(Color.GRAY);
            }
            field.setBorder(BorderFactory.createLineBorder(Color.WHITE, 1));
        }
    });
}

    
    private void styleComponents() {
    Font fieldFont = new Font("Segoe UI", Font.PLAIN, 12);
    JTextField[] fields = {
        nameTxt, routeIdTxt, depotIdTxt, startTimeTxt, departureTimesTxt
    };

    String[] placeholders = {
        "Name", "Route ID", "Depot ID", "Start Time", "Departure Times"
    };

    for (int i = 0; i < fields.length; i++) {
        fields[i].setFont(fieldFont);
        fields[i].setBorder(BorderFactory.createLineBorder(Color.WHITE, 1));
        addPlaceholderBehavior(fields[i], placeholders[i]);
    }

    // Style the button
    addButton.setBackground(Color.WHITE);
    addButton.setForeground(Color.BLACK);
    addButton.setOpaque(true);
    addButton.setBorderPainted(false);
    addButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    addButton.setFont(new Font("Segoe UI", Font.PLAIN, 12));
    addButton.setPreferredSize(new Dimension(160, 23));

    addButton.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            addButton.setBackground(Color.green);
        }

        @Override
        public void mouseExited(MouseEvent e) {
            addButton.setBackground(Color.WHITE);
        }
    });
}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        //        new AddScheduleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addSchedulePanel;
    private javax.swing.JTextField departureTimesTxt;
    private javax.swing.JTextField depotIdTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField routeIdTxt;
    private javax.swing.JTextField startTimeTxt;
    // End of variables declaration//GEN-END:variables
}
