package main;

import employees.Driver;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;

/**
 *
 * @author Handsome Onojerame
 */
public class DriverMenuGUI extends javax.swing.JFrame {
    private Database database;
    private String driverId;
    private Driver driver;
    /**
     * Creates new form DriverMenuGUI
     */
    public DriverMenuGUI(Database db, String driverID) {
        initComponents();
        this.database = db;
        this.driverId = driverID;
        this.driver = db.getEmployeeManagement().getDriverById(driverID);

        setLocationRelativeTo(null);
        
        headerNamelbl.setText(this.driver.getName());
        headerIDlbl.setText("Driver ID: " + this.driverId);
        
        headerNamelbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        headerIDlbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        
        assignmentBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        assignmentBtn.setPreferredSize(new Dimension(155, 23));
        passengersBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        passengersBtn.setPreferredSize(new Dimension(155, 23));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        logoutBtn.setPreferredSize(new Dimension(155, 23));
        schedulesBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        schedulesBtn.setPreferredSize(new Dimension(155, 23));
        
        addHoverEffect(assignmentBtn, Color.WHITE, Color.GREEN);
        addHoverEffect(passengersBtn, Color.WHITE, Color.GREEN);
        addHoverEffect(logoutBtn, Color.WHITE, Color.GREEN);
        addHoverEffect(schedulesBtn, Color.WHITE, Color.GREEN);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        headerNamelbl = new javax.swing.JLabel();
        headerIDlbl = new javax.swing.JLabel();
        assignmentBtn = new javax.swing.JButton();
        passengersBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        schedulesBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 224, 223));

        jPanel2.setBackground(new java.awt.Color(16, 32, 47));

        headerNamelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerNamelbl.setForeground(new java.awt.Color(255, 255, 255));
        headerNamelbl.setText("Lauren Smith");

        headerIDlbl.setForeground(new java.awt.Color(255, 255, 255));
        headerIDlbl.setText("Driver ID: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(headerNamelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerIDlbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        assignmentBtn.setText("View Assignment");

        passengersBtn.setText("View Passengers");

        logoutBtn.setText("Logout");

        schedulesBtn.setText("View All Schedules");

        txtField.setBackground(new java.awt.Color(16, 32, 47));
        txtField.setForeground(new java.awt.Color(255, 255, 255));
        txtField.setText("jTextField1");
        txtField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtField.setEnabled(false);
        txtField.setFocusable(false);
        jScrollPane1.setViewportView(txtField);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passengersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(schedulesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(assignmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(assignmentBtn)
                        .addGap(18, 18, 18)
                        .addComponent(passengersBtn)
                        .addGap(18, 18, 18)
                        .addComponent(schedulesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBtn)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    private void addHoverEffect(final JButton button, final Color normal, final Color hover) {
    button.setOpaque(true);
    button.setBackground(normal);
    button.setBorderPainted(false);

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hover);
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normal);
            
        }
    });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignmentBtn;
    private javax.swing.JLabel headerIDlbl;
    private javax.swing.JLabel headerNamelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton passengersBtn;
    private javax.swing.JButton schedulesBtn;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
