package main;

import bus.Bus;
import depot.DepotManager;
import employees.Driver;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JButton;
import main.DriverAssignment;
import main.RouteAssignment;

/**
 *
 * @author Handsome Onojerame
 */
public class DriverMenuGUI extends javax.swing.JFrame {
    private Database database;
    private String driverId;
    private Driver driver;
    private Dispatcher dispatcher;
    private ArrayList <DriverAssignment> driverAssignment;
    private ArrayList <RouteAssignment> routeAssignment;
    /**
     * Creates new form DriverMenuGUI
     */
    public DriverMenuGUI(Database db, String driverID) {
        initComponents();
        this.database = db;
        this.driverId = driverID;
        this.driver = db.getEmployeeManagement().getDriverById(driverID);
        this.dispatcher = db.getDispatcher();
        this.driverAssignment = this.dispatcher.getAllDriverAssignments();
        this.routeAssignment = this.dispatcher.getAllRouteAssignments();

        setLocationRelativeTo(null);
        
        headerNamelbl.setText(this.driver.getName());
        headerIDlbl.setText("Driver ID: " + this.driverId);
        
        headerNamelbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        headerIDlbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        
        assignmentBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        assignmentBtn.setPreferredSize(new Dimension(155, 23));
        passengersBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        passengersBtn.setPreferredSize(new Dimension(155, 23));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        logoutBtn.setPreferredSize(new Dimension(155, 23));
        schedulesBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        schedulesBtn.setPreferredSize(new Dimension(155, 23));
        
        addHoverEffect(assignmentBtn, Color.WHITE, Color.GREEN);
        addHoverEffect(passengersBtn, Color.WHITE, Color.GREEN);
        addHoverEffect(logoutBtn, Color.WHITE, Color.GREEN);
        addHoverEffect(schedulesBtn, Color.WHITE, Color.GREEN);
        
        txtArea.setEditable(false);
        txtArea.setLineWrap(true);
        txtArea.setWrapStyleWord(true);
        txtArea.setBackground(new java.awt.Color(16, 32, 47));
        txtArea.setForeground(java.awt.Color.WHITE);
        txtArea.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        jScrollPane1.setViewportView(txtArea);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        headerNamelbl = new javax.swing.JLabel();
        headerIDlbl = new javax.swing.JLabel();
        assignmentBtn = new javax.swing.JButton();
        passengersBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        schedulesBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 224, 223));

        jPanel2.setBackground(new java.awt.Color(16, 32, 47));

        headerNamelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerNamelbl.setForeground(new java.awt.Color(255, 255, 255));
        headerNamelbl.setText("Lauren Smith");

        headerIDlbl.setForeground(new java.awt.Color(255, 255, 255));
        headerIDlbl.setText("Driver ID: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(headerNamelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerIDlbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        assignmentBtn.setText("View Assignment");
        assignmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentBtnActionPerformed(evt);
            }
        });

        passengersBtn.setText("View Passengers");

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        schedulesBtn.setText("View All Schedules");
        schedulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedulesBtnActionPerformed(evt);
            }
        });

        txtArea.setBackground(new java.awt.Color(16, 32, 47));
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passengersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(schedulesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(assignmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(assignmentBtn)
                        .addGap(18, 18, 18)
                        .addComponent(passengersBtn)
                        .addGap(18, 18, 18)
                        .addComponent(schedulesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBtn)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentBtnActionPerformed
                                              
        StringBuilder output = new StringBuilder();

        // Find the driver's bus assignment
        Bus assignedBus = null;
        for (DriverAssignment da : driverAssignment) {
            if (da.getDriver().getEmployeeID().equals(driver.getEmployeeID())) {
                assignedBus = da.getBus();
                output.append("🚍 Bus Assignment:\n");
                output.append("• Bus ID: ").append(assignedBus.getBusId()).append("\n");
                output.append("• Make/Model: ").append(assignedBus.getMake())
                    .append(" ").append(assignedBus.getModel()).append("\n\n");
                break;
            }
        }

        // Find the route assigned to the same bus
        if (assignedBus != null) {
         for (RouteAssignment ra : routeAssignment) {
            if (ra.getBus().getBusId() == assignedBus.getBusId()) {
                Route route = ra.getRoute();
                output.append("🗺️ Route Assignment:\n");
                output.append("• Route ID: ").append(route.getRouteID()).append("\n");
                output.append("• Name: ").append(route.getName()).append("\n");

                if (route.getStops() != null && !route.getStops().isEmpty()) {
                    output.append("• Stops: ");
                    for (int i = 0; i < route.getStops().size(); i++) {
                        output.append(route.getStops().get(i).getName());
                        if (i < route.getStops().size() - 1) output.append(", ");
                    }
                    output.append("\n");
                } else {
                    output.append("• No stops assigned.\n");
                }
                break;
            }
        }
        }

        if (output.length() == 0) {
        output.append("No assignment found for this driver.");
        }

        txtArea.setText(output.toString());


    }//GEN-LAST:event_assignmentBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void schedulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedulesBtnActionPerformed
        if (database.getScheduleManager() != null && database.getRouteManager() != null && database.getDepotManager() != null) {
            new ViewScheduleGUI(database.getScheduleManager(), database.getRouteManager(), database.getDepotManager()).setVisible(true);
        } else {
            // Create new instances if not provided
            ScheduleManager sm = new ScheduleManager();
            RouteManager rm = new RouteManager();
            DepotManager dm = new DepotManager();
            
            // Load data
            sm.loadSchedulesFromCSV(rm, dm);
            
            new ViewScheduleGUI(sm, rm, dm).setVisible(true);
        }
    }//GEN-LAST:event_schedulesBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    private void addHoverEffect(final JButton button, final Color normal, final Color hover) {
    button.setOpaque(true);
    button.setBackground(normal);
    button.setBorderPainted(false);

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hover);
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normal);
            
        }
    });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignmentBtn;
    private javax.swing.JLabel headerIDlbl;
    private javax.swing.JLabel headerNamelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton passengersBtn;
    private javax.swing.JButton schedulesBtn;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
