/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Owner
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        initComponents();
        
        addHoverEffect(bookTicketMainMenuBtn, Color.LIGHT_GRAY, Color.GREEN);
        addHoverEffect(ViewSchedulesMainMenuBtn, Color.LIGHT_GRAY, Color.GREEN);
        addHoverEffect(EmployeeLoginMainMenuBtn, Color.LIGHT_GRAY, Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuContentPanel = new javax.swing.JPanel();
        bookTicketMainMenuBtn = new javax.swing.JButton();
        ViewSchedulesMainMenuBtn = new javax.swing.JButton();
        EmployeeLoginMainMenuBtn = new javax.swing.JButton();
        welcomeHeader1 = new javax.swing.JLabel();
        welcomeHeader2 = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(null);

        mainMenuContentPanel.setOpaque(false);

        bookTicketMainMenuBtn.setText("Book Ticket");
        bookTicketMainMenuBtn.setBorderPainted(false);
        bookTicketMainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketMainMenuBtnActionPerformed(evt);
            }
        });

        ViewSchedulesMainMenuBtn.setText("View Schedules");
        ViewSchedulesMainMenuBtn.setBorderPainted(false);
        ViewSchedulesMainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSchedulesMainMenuBtnActionPerformed(evt);
            }
        });

        EmployeeLoginMainMenuBtn.setText("Employee Login");
        EmployeeLoginMainMenuBtn.setBorderPainted(false);

        welcomeHeader1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        welcomeHeader1.setText("WELCOME TO BUS ");

        welcomeHeader2.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        welcomeHeader2.setForeground(new java.awt.Color(0, 153, 0));
        welcomeHeader2.setText("COMPANY!");

        javax.swing.GroupLayout mainMenuContentPanelLayout = new javax.swing.GroupLayout(mainMenuContentPanel);
        mainMenuContentPanel.setLayout(mainMenuContentPanelLayout);
        mainMenuContentPanelLayout.setHorizontalGroup(
            mainMenuContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContentPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(mainMenuContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainMenuContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EmployeeLoginMainMenuBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(ViewSchedulesMainMenuBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookTicketMainMenuBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        mainMenuContentPanelLayout.setVerticalGroup(
            mainMenuContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContentPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(welcomeHeader1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeHeader2)
                .addGap(64, 64, 64)
                .addComponent(bookTicketMainMenuBtn)
                .addGap(18, 18, 18)
                .addComponent(ViewSchedulesMainMenuBtn)
                .addGap(18, 18, 18)
                .addComponent(EmployeeLoginMainMenuBtn)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        getContentPane().add(mainMenuContentPanel);
        mainMenuContentPanel.setBounds(0, 0, 720, 460);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/background.png"))); // NOI18N
        backGround.setLabelFor(this);
        backGround.setText("background");
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 715, 460);

        setSize(new java.awt.Dimension(725, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookTicketMainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketMainMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookTicketMainMenuBtnActionPerformed

    private void ViewSchedulesMainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSchedulesMainMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewSchedulesMainMenuBtnActionPerformed
    
    private void addHoverEffect(final JButton button, final Color normal, final Color hover) {
    button.setOpaque(true);
    button.setBackground(normal);
    button.setBorderPainted(false);

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hover);
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normal);
        }
    });
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeLoginMainMenuBtn;
    private javax.swing.JButton ViewSchedulesMainMenuBtn;
    private javax.swing.JLabel backGround;
    private javax.swing.JButton bookTicketMainMenuBtn;
    private javax.swing.JPanel mainMenuContentPanel;
    private javax.swing.JLabel welcomeHeader1;
    private javax.swing.JLabel welcomeHeader2;
    // End of variables declaration//GEN-END:variables
}
