
package main;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * GUI for managing an existing route
 * @author Adrian Zielinski
 */
public class ManageRouteGUI extends javax.swing.JFrame {
    
    private Database database;
    private AdminMenuGUI adminMenuGUI;
    private Route selectedRoute;
    private ArrayList<String> stopsListData;
    
    /**
     * Creates new form ManageRouteGUI
     * @param database the database
     * @param adminMenuGUI the parent AdminMenuGUI
     */
    public ManageRouteGUI(Database database, AdminMenuGUI adminMenuGUI) {
        // initialize instance variables
        this.database = database;
        this.adminMenuGUI = adminMenuGUI;
        initComponents();
        
        // set focus setting on load
        setAutoRequestFocus(false);
        
        // initialize the list data for bus stops
        stopsListData = new ArrayList<>();
        
        // populate the route combo box
        populateRouteComboBox();
        
        // style text fields
        applyTextFieldEffects(routeNameTxt, "Route Name");
        applyTextFieldEffects(stopNameTxt, "Stop Name");
        applyTextFieldEffects(distanceTxt, "Distance to Next Stop(miles)");

        // style buttons
        styleButton(addStopButton);
        styleButton(removeStopButton);
        styleButton(updateRouteButton);
        styleButton(assignDriverButton);
        styleButton(unassignDriverButton);
        
        // style combo box
        styleComboBox(routeComboBox);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageRoutePanel = new javax.swing.JPanel();
        routeLabel = new javax.swing.JLabel();
        routeComboBox = new javax.swing.JComboBox<>();
        routeNameTxt = new javax.swing.JTextField();
        stopsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stopsList = new javax.swing.JList<>();
        addStopButton = new javax.swing.JButton();
        removeStopButton = new javax.swing.JButton();
        updateRouteButton = new javax.swing.JButton();
        stopNameTxt = new javax.swing.JTextField();
        distanceTxt = new javax.swing.JTextField();
        assignDriverButton = new javax.swing.JButton();
        unassignDriverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Route");

        manageRoutePanel.setBackground(new java.awt.Color(215, 224, 223));

        routeLabel.setText("Select Route:");

        routeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeComboBoxActionPerformed(evt);
            }
        });

        routeNameTxt.setForeground(new java.awt.Color(153, 153, 153));
        routeNameTxt.setText("Route Name");

        stopsLabel.setText("Bus Stops:");

        jScrollPane1.setViewportView(stopsList);

        addStopButton.setText("Add Stop");
        addStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStopButtonActionPerformed(evt);
            }
        });

        removeStopButton.setText("Remove Stop");
        removeStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStopButtonActionPerformed(evt);
            }
        });

        updateRouteButton.setText("Update Route");
        updateRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRouteButtonActionPerformed(evt);
            }
        });

        stopNameTxt.setForeground(new java.awt.Color(153, 153, 153));
        stopNameTxt.setText("Stop Name");

        distanceTxt.setForeground(new java.awt.Color(153, 153, 153));
        distanceTxt.setText("Distance to Next Stop(miles)");
        
        assignDriverButton.setText("Assign Driver");
        assignDriverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDriverButtonActionPerformed(evt);
            }
        });
        
        unassignDriverButton.setText("Unassign Driver");
        unassignDriverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unassignDriverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageRoutePanelLayout = new javax.swing.GroupLayout(manageRoutePanel);
        manageRoutePanel.setLayout(manageRoutePanelLayout);
        manageRoutePanelLayout.setHorizontalGroup(
            manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRoutePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageRoutePanelLayout.createSequentialGroup()
                                .addComponent(routeLabel)
                                .addGap(10, 10, 10)
                                .addComponent(routeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stopsLabel))
                        .addGap(20, 20, 20))
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateRouteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assignDriverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unassignDriverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(distanceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(stopNameTxt)
                    .addComponent(routeNameTxt))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        manageRoutePanelLayout.setVerticalGroup(
            manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRoutePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addComponent(routeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stopNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(distanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addStopButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeStopButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateRouteButton)
                        .addGap(18, 18, 18)
                        .addComponent(assignDriverButton)
                        .addGap(18, 18, 18)
                        .addComponent(unassignDriverButton))
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routeLabel)
                            .addComponent(routeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(stopsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRoutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRoutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void routeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeComboBoxActionPerformed
        // get the selected route
        String selectedItem = (String) routeComboBox.getSelectedItem();
        
        if (selectedItem != null) {
            // extract the route ID from the selected item
            String routeId = selectedItem.split(" - ")[0];
            
            // find the route by ID
            selectedRoute = database.getRouteManager().getRouteById(routeId);
            
            if (selectedRoute != null) {
                // update the route name field
                routeNameTxt.setText(selectedRoute.getName());
                
                // update the stops list
                updateStopsList();
            }
        }
    }//GEN-LAST:event_routeComboBoxActionPerformed
    /**
     * Details the action to take when the add stop button is clicked
     * @param evt 
     */
    private void addStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStopButtonActionPerformed
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String stopName = stopNameTxt.getText().trim();
        String distanceStr = distanceTxt.getText().trim();
        
        if (stopName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a stop name.", 
                    "Missing Information", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double distance = Double.parseDouble(distanceStr);

        // create and add the bus stop
        BusStop busStop = new BusStop(stopName, distance);
        selectedRoute.addStop(busStop);

        // update the stops list
        updateStopsList();

        // clear the input fields
        stopNameTxt.setText("");
        distanceTxt.setText("");
            
    }//GEN-LAST:event_addStopButtonActionPerformed
/**
 * Details the action to take when the remove button is clicked
 * @param evt 
 */
    private void removeStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStopButtonActionPerformed
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int selectedIndex = stopsList.getSelectedIndex();
        
        if (selectedIndex >= 0) {
            // get the selected stop
            ArrayList<BusStop> stops = selectedRoute.getStops();
            
            if (selectedIndex < stops.size()) {
                // remove the stop from the route
                BusStop stopToRemove = stops.get(selectedIndex);
                selectedRoute.removeStop(stopToRemove);
                
                // update the stops list
                updateStopsList();
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Please select a stop to remove.", 
                    "No Stop Selected", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeStopButtonActionPerformed

    /**
     * Details the action to take when the update button is clicked
     * @param evt 
     */
    private void updateRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRouteButtonActionPerformed
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String routeName = routeNameTxt.getText().trim();
        
        if (routeName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a route name.", 
                    "Missing Information", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // update the route name
        selectedRoute.setName(routeName);
        
        // save changes to CSV
        database.getRouteManager().saveRoutesToCSV();
        
        // refresh the route table in AdminMenuGUI
        if (adminMenuGUI != null) {
            adminMenuGUI.populateRouteTable();
        }
        
        // refresh the route combo box
        populateRouteComboBox();
        
        JOptionPane.showMessageDialog(this, 
                "Route updated successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_updateRouteButtonActionPerformed
    
    /**
     * handles the assign driver button click event
     * assigns a driver to the bus assigned to the selected route
     * @param evt the action event
     */
    private void assignDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // get the bus assigned to this route
        bus.Bus bus = database.getDispatcher().getBusForRoute(selectedRoute);
        
        if (bus == null) {
            JOptionPane.showMessageDialog(this, 
                    "No bus is assigned to this route. Please assign a bus first.", 
                    "No Bus Assigned", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // check if the bus already has a driver
        employees.Driver currentDriver = database.getDispatcher().getDriverForBus(bus);
        if (currentDriver != null) {
            JOptionPane.showMessageDialog(this, 
                    "This bus already has a driver assigned: " + currentDriver.getName(), 
                    "Driver Already Assigned", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // get all available drivers
        java.util.ArrayList<employees.Driver> availableDrivers = new java.util.ArrayList<>();
        for (employees.Employee employee : database.getEmployeeManagement().getAllEmployees()) {
            if (employee instanceof employees.Driver) {
                employees.Driver driver = (employees.Driver) employee;
                if (driver.getAvailability()) {
                    availableDrivers.add(driver);
                }
            }
        }
        
        // if there are no available drivers, show a message
        if (availableDrivers.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "No available drivers found.", 
                    "Assign Driver", 
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // create a dialog to select a driver
        String[] driverNames = new String[availableDrivers.size()];
        for (int i = 0; i < availableDrivers.size(); i++) {
            driverNames[i] = availableDrivers.get(i).getName() + " (ID: " + availableDrivers.get(i).getEmployeeID() + ")";
        }
        
        String selectedDriverName = (String) JOptionPane.showInputDialog(
                this,
                "Select a driver to assign to bus " + bus.getMake() + " " + bus.getModel() + " (ID: " + bus.getBusId() + ") for route " + selectedRoute.getName() + ":",
                "Assign Driver",
                JOptionPane.QUESTION_MESSAGE,
                null,
                driverNames,
                driverNames[0]);
        
        // if a driver was selected, assign them to the bus
        if (selectedDriverName != null) {
            int selectedIndex = -1;
            for (int i = 0; i < driverNames.length; i++) {
                if (driverNames[i].equals(selectedDriverName)) {
                    selectedIndex = i;
                    break;
                }
            }
            
            if (selectedIndex >= 0) {
                employees.Driver selectedDriver = availableDrivers.get(selectedIndex);
                boolean success = database.getDispatcher().assignDriverToBus(selectedDriver, bus);
                
                if (success) {
                    JOptionPane.showMessageDialog(this, 
                            "Driver " + selectedDriver.getName() + " assigned to bus successfully.", 
                            "Assign Driver", 
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, 
                            "Failed to assign driver to bus.", 
                            "Assign Driver", 
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    
    /**
     * handles the unassign driver button click event
     * removes a driver from the bus assigned to the selected route
     * @param evt the action event
     */
    private void unassignDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // get the bus assigned to this route
        bus.Bus bus = database.getDispatcher().getBusForRoute(selectedRoute);
        
        if (bus == null) {
            JOptionPane.showMessageDialog(this, 
                    "No bus is assigned to this route.", 
                    "No Bus Assigned", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // check if the bus has a driver
        employees.Driver driver = database.getDispatcher().getDriverForBus(bus);
        if (driver == null) {
            JOptionPane.showMessageDialog(this, 
                    "No driver is assigned to this bus.", 
                    "No Driver Assigned", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // confirm unassignment
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to unassign driver " + driver.getName() + " from bus " + bus.getMake() + " " + bus.getModel() + " (ID: " + bus.getBusId() + ")?",
                "Confirm Unassignment",
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            // remove the driver from the bus
            boolean success = database.getDispatcher().removeDriverFromBus(bus);
            
            if (success) {
                JOptionPane.showMessageDialog(this, 
                        "Driver unassigned from bus successfully.", 
                        "Unassign Driver", 
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Failed to unassign driver from bus.", 
                        "Unassign Driver", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * populates the route combo box with all available routes
     */
    private void populateRouteComboBox() {
        routeComboBox.removeAllItems();
        
        ArrayList<Route> routes = database.getRouteManager().getRoutes();
        
        for (Route route : routes) {
            routeComboBox.addItem(route.getRouteID() + " - " + route.getName());
        }
    }
    
    /**
     * updates the stops list with the current stops of the selected route
     */
    private void updateStopsList() {
        stopsListData.clear();
        
        if (selectedRoute != null) {
            ArrayList<BusStop> stops = selectedRoute.getStops();
            
            for (BusStop stop : stops) {
                stopsListData.add(stop.getName() + " (Distance: " + stop.getDistanceToNext() + " miles)");
            }
        }
        
        // update list
        stopsList.setListData(stopsListData.toArray(new String[0]));
    }
    
    /**
     * applies placeholder text and styling effects to a text field
     * @param field the text field to apply effects to
     * @param placeholder the placeholder text to display when the field is empty
     */
    private void applyTextFieldEffects(JTextField field, String placeholder) {
        field.setForeground(Color.GRAY);
        field.setText(placeholder);
        field.setBorder(BorderFactory.createLineBorder(Color.WHITE));

        field.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
                field.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(Color.GRAY);
                }
                field.setBorder(BorderFactory.createLineBorder(Color.WHITE));
            }
        });
    }
    
    /**
     * applies styling to a button including colors, font, and hover effects
     * @param button the button to style
     */
    private void styleButton(JButton button) {
        button.setBackground(Color.WHITE);
        button.setForeground(Color.BLACK);
        button.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        button.setPreferredSize(new Dimension(160, 23));
        button.setOpaque(true);
        button.setBorderPainted(false);
        button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Color hover = Color.green;

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(hover);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(Color.WHITE);
            }
        });
    }
    
    /**
     * applies styling to a combo box including colors, font, and focus effects
     * @param comboBox the combo box to style
     */
    private void styleComboBox(JComboBox<?> comboBox) {
    comboBox.setBackground(Color.WHITE);
    comboBox.setForeground(Color.BLACK);
    comboBox.setFont(new Font("Segoe UI", Font.PLAIN, 12));
    comboBox.setPreferredSize(new Dimension(160, 23));
    comboBox.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    comboBox.setBorder(BorderFactory.createLineBorder(Color.WHITE));

    comboBox.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            comboBox.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        }

        @Override
        public void focusLost(FocusEvent e) {
            comboBox.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStopButton;
    private javax.swing.JButton assignDriverButton;
    private javax.swing.JTextField distanceTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel manageRoutePanel;
    private javax.swing.JButton removeStopButton;
    private javax.swing.JComboBox<String> routeComboBox;
    private javax.swing.JLabel routeLabel;
    private javax.swing.JTextField routeNameTxt;
    private javax.swing.JTextField stopNameTxt;
    private javax.swing.JLabel stopsLabel;
    private javax.swing.JList<String> stopsList;
    private javax.swing.JButton unassignDriverButton;
    private javax.swing.JButton updateRouteButton;
    // End of variables declaration//GEN-END:variables
}
