/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * GUI for managing an existing route
 * @author Adrian Zielinski
 */
public class ManageRouteGUI extends javax.swing.JFrame {
    
    private Database database;
    private AdminMenuGUI adminMenuGUI;
    private Route selectedRoute;
    private DefaultListModel<String> stopsListModel;
    
    /**
     * Creates new form ManageRouteGUI
     * @param database the database
     * @param adminMenuGUI the parent AdminMenuGUI
     */
    public ManageRouteGUI(Database database, AdminMenuGUI adminMenuGUI) {
        this.database = database;
        this.adminMenuGUI = adminMenuGUI;
        initComponents();
        
        // initialize the list model for bus stops
        stopsListModel = new DefaultListModel<>();
        stopsList.setModel(stopsListModel);
        
        // populate the route combo box
        populateRouteComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageRoutePanel = new javax.swing.JPanel();
        routeLabel = new javax.swing.JLabel();
        routeComboBox = new javax.swing.JComboBox<>();
        routeNameLabel = new javax.swing.JLabel();
        routeNameTxt = new javax.swing.JTextField();
        stopsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stopsList = new javax.swing.JList<>();
        addStopButton = new javax.swing.JButton();
        removeStopButton = new javax.swing.JButton();
        updateRouteButton = new javax.swing.JButton();
        deleteRouteButton = new javax.swing.JButton();
        stopNameLabel = new javax.swing.JLabel();
        stopNameTxt = new javax.swing.JTextField();
        distanceLabel = new javax.swing.JLabel();
        distanceTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Route");

        manageRoutePanel.setBackground(new java.awt.Color(215, 224, 223));

        routeLabel.setText("Select Route:");

        routeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeComboBoxActionPerformed(evt);
            }
        });

        routeNameLabel.setText("Route Name:");

        stopsLabel.setText("Bus Stops:");

        jScrollPane1.setViewportView(stopsList);

        addStopButton.setText("Add Stop");
        addStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStopButtonActionPerformed(evt);
            }
        });

        removeStopButton.setText("Remove Stop");
        removeStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStopButtonActionPerformed(evt);
            }
        });

        updateRouteButton.setText("Update Route");
        updateRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRouteButtonActionPerformed(evt);
            }
        });

        deleteRouteButton.setText("Delete Route");
        deleteRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRouteButtonActionPerformed(evt);
            }
        });

        stopNameLabel.setText("Stop Name:");

        distanceLabel.setText("Distance to Next Stop (miles):");

        javax.swing.GroupLayout manageRoutePanelLayout = new javax.swing.GroupLayout(manageRoutePanel);
        manageRoutePanel.setLayout(manageRoutePanelLayout);
        manageRoutePanelLayout.setHorizontalGroup(
            manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRoutePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addComponent(routeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(routeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addComponent(routeNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(routeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopsLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stopNameLabel)
                            .addComponent(stopNameTxt)
                            .addComponent(distanceLabel)
                            .addComponent(distanceTxt)
                            .addComponent(addStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageRoutePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        manageRoutePanelLayout.setVerticalGroup(
            manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRoutePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeLabel)
                    .addComponent(routeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeNameLabel)
                    .addComponent(routeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopsLabel)
                    .addComponent(stopNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(manageRoutePanelLayout.createSequentialGroup()
                        .addComponent(stopNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(distanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addStopButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeStopButton))
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30)
                .addComponent(updateRouteButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRoutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRoutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void routeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeComboBoxActionPerformed
        // get the selected route
        String selectedItem = (String) routeComboBox.getSelectedItem();
        
        if (selectedItem != null) {
            // extract the route ID from the selected item
            String routeId = selectedItem.split(" - ")[0];
            
            // find the route by ID
            selectedRoute = database.getRouteManager().getRouteById(routeId);
            
            if (selectedRoute != null) {
                // update the route name field
                routeNameTxt.setText(selectedRoute.getName());
                
                // update the stops list
                updateStopsList();
            }
        }
    }//GEN-LAST:event_routeComboBoxActionPerformed

    private void addStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStopButtonActionPerformed
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String stopName = stopNameTxt.getText().trim();
        String distanceStr = distanceTxt.getText().trim();
        
        if (stopName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a stop name.", 
                    "Missing Information", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double distance = Double.parseDouble(distanceStr);

        // create and add the bus stop
        BusStop busStop = new BusStop(stopName, distance);
        selectedRoute.addStop(busStop);

        // update the stops list
        updateStopsList();

        // clear the input fields
        stopNameTxt.setText("");
        distanceTxt.setText("");
            
    }//GEN-LAST:event_addStopButtonActionPerformed

    private void removeStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStopButtonActionPerformed
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int selectedIndex = stopsList.getSelectedIndex();
        
        if (selectedIndex >= 0) {
            // get the selected stop
            ArrayList<BusStop> stops = selectedRoute.getStops();
            
            if (selectedIndex < stops.size()) {
                // remove the stop from the route
                BusStop stopToRemove = stops.get(selectedIndex);
                selectedRoute.removeStop(stopToRemove);
                
                // update the stops list
                updateStopsList();
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Please select a stop to remove.", 
                    "No Stop Selected", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeStopButtonActionPerformed

    private void updateRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRouteButtonActionPerformed
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String routeName = routeNameTxt.getText().trim();
        
        if (routeName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Please enter a route name.", 
                    "Missing Information", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // update the route name
        selectedRoute.setName(routeName);
        
        // save changes to CSV
        database.getRouteManager().saveRoutesToCSV();
        
        // refresh the route table in AdminMenuGUI
        if (adminMenuGUI != null) {
            adminMenuGUI.populateRouteTable();
        }
        
        // refresh the route combo box
        populateRouteComboBox();
        
        JOptionPane.showMessageDialog(this, 
                "Route updated successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_updateRouteButtonActionPerformed
    
    private void deleteRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRouteButtonActionPerformed
        if (selectedRoute == null) {
            JOptionPane.showMessageDialog(this, 
                    "Please select a route first.", 
                    "No Route Selected", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete route '" + selectedRoute.getName() + "'?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            // remove the route
            database.getRouteManager().removeRoute(selectedRoute);
            
            // refresh the route table in AdminMenuGUI
            if (adminMenuGUI != null) {
                adminMenuGUI.populateRouteTable();
            }
            
            // refresh the route combo box
            populateRouteComboBox();
            
            // clear the form
            routeNameTxt.setText("");
            stopsListModel.clear();
            selectedRoute = null;
            
            JOptionPane.showMessageDialog(this, 
                    "Route deleted successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteRouteButtonActionPerformed

    /**
     * populates the route combo box with all available routes
     */
    private void populateRouteComboBox() {
        routeComboBox.removeAllItems();
        
        ArrayList<Route> routes = database.getRouteManager().getRoutes();
        
        for (Route route : routes) {
            routeComboBox.addItem(route.getRouteID() + " - " + route.getName());
        }
    }
    
    /**
     * updates the stops list with the current stops of the selected route
     */
    private void updateStopsList() {
        stopsListModel.clear();
        
        if (selectedRoute != null) {
            ArrayList<BusStop> stops = selectedRoute.getStops();
            
            for (BusStop stop : stops) {
                stopsListModel.addElement(stop.getName() + " (Distance: " + stop.getDistanceToNext() + " miles)");
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRouteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ManageRouteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStopButton;
    private javax.swing.JButton deleteRouteButton;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JTextField distanceTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel manageRoutePanel;
    private javax.swing.JButton removeStopButton;
    private javax.swing.JComboBox<String> routeComboBox;
    private javax.swing.JLabel routeLabel;
    private javax.swing.JLabel routeNameLabel;
    private javax.swing.JTextField routeNameTxt;
    private javax.swing.JLabel stopNameLabel;
    private javax.swing.JTextField stopNameTxt;
    private javax.swing.JLabel stopsLabel;
    private javax.swing.JList<String> stopsList;
    private javax.swing.JButton updateRouteButton;
    // End of variables declaration//GEN-END:variables
}
