/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Owner
 */
public class PassengerLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form PassengerLoginGUI
     */
    public PassengerLoginGUI() {
        initComponents();
        setupUsernameBehavior();
        setupPasswordBehavior();
        setupSignUpLabelHover();
        setupSignUpLabelAction();
        addHoverEffect(loginBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userNameField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        SignUpLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        continueAsGuestLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameField.setForeground(new java.awt.Color(153, 153, 153));
        userNameField.setText("Username");
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 204, 0));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setBorderPainted(false);

        SignUpLabel.setForeground(new java.awt.Color(255, 0, 51));
        SignUpLabel.setText("Sign up");

        passwordField.setForeground(new java.awt.Color(153, 153, 153));
        passwordField.setText("password");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        continueAsGuestLabel.setForeground(new java.awt.Color(255, 0, 51));
        continueAsGuestLabel.setText("Continue As Guest");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(SignUpLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(continueAsGuestLabel)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn)
                .addGap(18, 18, 18)
                .addComponent(SignUpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueAsGuestLabel)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed
    
    
    // Set up focus behaviour for Username text field
    private void setupUsernameBehavior() {
    userNameField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (userNameField.getText().equals("Username")) {
                userNameField.setText("");
                userNameField.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (userNameField.getText().isEmpty()) {
                userNameField.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                userNameField.setText("Username");
            }
        }
    });
    }
    
    // set up password focus behaviour for password field
    private void setupPasswordBehavior() {
    passwordField.setEchoChar((char)0); // No masking initially (for placeholder)

    passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            String pwd = new String(passwordField.getPassword());
            if (pwd.equals("password")) {
                passwordField.setText("");
                passwordField.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
                passwordField.setEchoChar('•'); // Restore masking when typing
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            String pwd = new String(passwordField.getPassword());
            if (pwd.isEmpty()) {
                passwordField.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                passwordField.setText("password");
                passwordField.setEchoChar((char)0); // No masking for placeholder
            }
        }
    });
    }
    
    private void setupSignUpLabelHover() {
    SignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            SignUpLabel.setForeground(new java.awt.Color(0, 153, 0)); // Hover color (light blue)
            SignUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Change cursor to hand
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            SignUpLabel.setForeground(Color.RED); // Original color (green)
            SignUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Restore cursor
        }
    });
    }
    
    private void setupSignUpLabelAction() {
    SignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            openSignUpForm();
        }
    });
    }
    
    private void openSignUpForm() {
    // Open the signup form
    //SignUpFormGUI signUpForm = new SignUpFormGUI(); // Assuming you create this JFrame
    //signUpForm.setVisible(true);

    // Optional: Close or hide the current login window if you want
    // this.dispose();
    }
    
    private void addHoverEffect(final JButton button) {
    button.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            loginBtn.setBackground(Color.LIGHT_GRAY); // Gray background on hover
            loginBtn.setForeground(new java.awt.Color(0, 153, 0)); // Green text on hover
            loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Optional: Hand cursor
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            loginBtn.setBackground(new java.awt.Color(0, 204, 0)); // Restore green background
            loginBtn.setForeground(Color.WHITE); // Restore white text
            loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Restore default cursor
        }
    });
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.JLabel continueAsGuestLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
