/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import payment.Payment;
import ticket.*;

/**
 * GUI for the ticket menu
 * @author Handsome Onojerame
 */
public class TicketMenuGUI extends javax.swing.JFrame {
    private Database database;
    private Passenger passenger;
    private String scheduleName;
    
    /**
     * Creates new form TicketMenuGUI
     */
    public TicketMenuGUI(Database db, Passenger initialPassenger, String schedule) {
        this.database = db;
        this.passenger = initialPassenger;
        this.scheduleName = schedule;
        initComponents();
        setLocationRelativeTo(null);
        setAutoRequestFocus(false);

        // Placeholder behavior
        setUpFieldFocus(cardNumberField, "Card number");
        setUpFieldFocus(expirationDateField, "Expiration date");
        setUpFieldFocus(cvvField, "Cvv");

        // Button styling
        payBtn.setBackground(Color.WHITE);
        payBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        payBtn.setPreferredSize(new java.awt.Dimension(cardNumberField.getPreferredSize().width, 30));
        addHoverEffect(payBtn, Color.WHITE, Color.green); // white to green

        ticketSelectedlbl.setText("Ticket Selected: " + schedule); 
    }
    
    /**
     * Sets up focus effects for the text fields
     * @param field
     * @param placeholder 
     */
    private void setUpFieldFocus(javax.swing.JTextField field, String placeholder) {
    field.setForeground(new Color(102, 102, 102));
    field.setText(placeholder);

    field.addFocusListener(new java.awt.event.FocusAdapter() {
        Border defaultBorder = BorderFactory.createLineBorder(Color.white, 1);
        Border focusBorder = BorderFactory.createLineBorder(new Color(0, 204, 51), 2);
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(Color.BLACK);
                field.setBorder(focusBorder);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(new Color(102, 102, 102));
                field.setBorder(defaultBorder);
            }
        }
    });
}

    /**
     * Adds hover effects to buttons
     * @param button
     * @param normal
     * @param hover 
     */
    private void addHoverEffect(final javax.swing.JButton button, final Color normal, final Color hover) {
    button.setOpaque(true);
    button.setBackground(normal);
    button.setBorderPainted(false);

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hover);
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normal);
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ticketSelectedlbl = new javax.swing.JLabel();
        ticketPricelbl = new javax.swing.JLabel();
        fillInInfolbl = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        expirationDateField = new javax.swing.JTextField();
        cvvField = new javax.swing.JTextField();
        payBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 32, 47));

        ticketSelectedlbl.setForeground(new java.awt.Color(255, 255, 255));
        ticketSelectedlbl.setText("Ticket Selected: ");

        ticketPricelbl.setForeground(new java.awt.Color(255, 255, 255));
        ticketPricelbl.setText("Ticket Price: $3.00");

        fillInInfolbl.setForeground(new java.awt.Color(255, 255, 255));
        fillInInfolbl.setText("Please fill in your payment information below:");

        cardNumberField.setForeground(new java.awt.Color(102, 102, 102));
        cardNumberField.setText("Card number");
        cardNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        expirationDateField.setForeground(new java.awt.Color(102, 102, 102));
        expirationDateField.setText("Expiration date");
        expirationDateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cvvField.setForeground(new java.awt.Color(102, 102, 102));
        cvvField.setText("Cvv");
        cvvField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        payBtn.setText("Pay");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketSelectedlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketPricelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fillInInfolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cvvField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(expirationDateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addComponent(payBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardNumberField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(ticketSelectedlbl)
                .addGap(18, 18, 18)
                .addComponent(ticketPricelbl)
                .addGap(18, 18, 18)
                .addComponent(fillInInfolbl)
                .addGap(18, 18, 18)
                .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(expirationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(payBtn)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * processes the payment and books ticket when Pay button is clicked
     * @param evt 
     */
    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        String card = cardNumberField.getText().trim();
        String expiration = expirationDateField.getText().trim();
        String cvv = cvvField.getText().trim();

        // Check if any field is empty
        if (card.equals("Card number") || expiration.equals("Expiration date") || cvv.equals("Cvv")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all payment fields.", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Stop execution if fields are incomplete
        }

        // Proceed with booking and payment
        database.getTicketIssuer().bookTicket(passenger, database.getScheduleManager().getScheduleByName(scheduleName));
        
        database.getTicketIssuer().getTicketManager().saveTicketsToCSV();

        database.getPaymentManager().processPayment(passenger, 3.00, card, expiration, database.getPaymentManager());


        javax.swing.JOptionPane.showMessageDialog(this, "Payment Successful!");
        this.dispose();
    }//GEN-LAST:event_payBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JTextField cvvField;
    private javax.swing.JTextField expirationDateField;
    private javax.swing.JLabel fillInInfolbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton payBtn;
    private javax.swing.JLabel ticketPricelbl;
    private javax.swing.JLabel ticketSelectedlbl;
    // End of variables declaration//GEN-END:variables
}
