/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;

/**
 *
 * @author Owner
 */
public class UpdatePassengerProfileGUI extends javax.swing.JFrame {
    private Border defaultBorder = BorderFactory.createLineBorder(Color.white, 1);
    private Border focusBorder = BorderFactory.createLineBorder(new Color(0, 204, 51), 2);
    private Passenger passenger;
    private PassengerManager passengerManager;
    private passengerDashboardGUI passengerDashboard;
    /**
     * Creates new form UpdatePassengerProfileGUI
     */
    public UpdatePassengerProfileGUI(Passenger initPassenger,PassengerManager pm, passengerDashboardGUI dashboard) {
        this.passenger = initPassenger;
        this.passengerManager = pm;
        this.passengerDashboard = dashboard;
        initComponents();
        setAutoRequestFocus(false);
        setLocationRelativeTo(null);
        deleteAccountBtn1.setBackground(Color.white);
        saveUpdateBtn.setForeground(Color.black);
        
        addHoverEffect(deleteAccountBtn1, Color.WHITE, Color.GREEN);
        addHoverEffect(saveUpdateBtn, Color.WHITE, Color.GREEN);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameUpdatetxt = new javax.swing.JTextField();
        phoneNumberUpdatetxt = new javax.swing.JTextField();
        emailUpdatetxt = new javax.swing.JTextField();
        saveUpdateBtn = new javax.swing.JButton();
        deleteAccountBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 224, 223));

        nameUpdatetxt.setForeground(new java.awt.Color(153, 153, 153));
        nameUpdatetxt.setText("Update Name");
        nameUpdatetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        nameUpdatetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameUpdatetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameUpdatetxtFocusLost(evt);
            }
        });
        nameUpdatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUpdatetxtActionPerformed(evt);
            }
        });

        phoneNumberUpdatetxt.setForeground(new java.awt.Color(153, 153, 153));
        phoneNumberUpdatetxt.setText("Update Phone Number");
        phoneNumberUpdatetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        phoneNumberUpdatetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberUpdatetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumberUpdatetxtFocusLost(evt);
            }
        });
        phoneNumberUpdatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberUpdatetxtActionPerformed(evt);
            }
        });

        emailUpdatetxt.setForeground(new java.awt.Color(153, 153, 153));
        emailUpdatetxt.setText("Update Email");
        emailUpdatetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        emailUpdatetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailUpdatetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailUpdatetxtFocusLost(evt);
            }
        });

        saveUpdateBtn.setText("Save Update");
        saveUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUpdateBtnActionPerformed(evt);
            }
        });

        deleteAccountBtn1.setText("Delete Account");
        deleteAccountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAccountBtn1))
                    .addComponent(emailUpdatetxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameUpdatetxt)
                    .addComponent(phoneNumberUpdatetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(nameUpdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneNumberUpdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailUpdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveUpdateBtn)
                    .addComponent(deleteAccountBtn1))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumberUpdatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberUpdatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberUpdatetxtActionPerformed

    private void nameUpdatetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameUpdatetxtFocusGained
        if (nameUpdatetxt.getText().equals("Update Name")) {
                nameUpdatetxt.setText("");
                nameUpdatetxt.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
                nameUpdatetxt.setBorder(focusBorder);
            }       
    }//GEN-LAST:event_nameUpdatetxtFocusGained

    private void nameUpdatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUpdatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameUpdatetxtActionPerformed

    private void nameUpdatetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameUpdatetxtFocusLost
        if (nameUpdatetxt.getText().isEmpty()) {
                nameUpdatetxt.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                nameUpdatetxt.setText("Update Name");
                nameUpdatetxt.setBorder(defaultBorder);
            } 
    }//GEN-LAST:event_nameUpdatetxtFocusLost

    private void phoneNumberUpdatetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberUpdatetxtFocusGained
        if (phoneNumberUpdatetxt.getText().equals("Update Phone Number")) {
                phoneNumberUpdatetxt.setText("");
                phoneNumberUpdatetxt.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
                phoneNumberUpdatetxt.setBorder(focusBorder);
            }   
    }//GEN-LAST:event_phoneNumberUpdatetxtFocusGained

    private void phoneNumberUpdatetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberUpdatetxtFocusLost
        if (phoneNumberUpdatetxt.getText().isEmpty()) {
                phoneNumberUpdatetxt.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                phoneNumberUpdatetxt.setText("Update Phone Number");
                phoneNumberUpdatetxt.setBorder(defaultBorder);
            } 
    }//GEN-LAST:event_phoneNumberUpdatetxtFocusLost

    private void emailUpdatetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUpdatetxtFocusGained
        if (emailUpdatetxt.getText().equals("Update Email")) {
                emailUpdatetxt.setText("");
                emailUpdatetxt.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
                emailUpdatetxt.setBorder(focusBorder);
            }
    }//GEN-LAST:event_emailUpdatetxtFocusGained

    private void emailUpdatetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUpdatetxtFocusLost
        if (emailUpdatetxt.getText().isEmpty()) {
                emailUpdatetxt.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                emailUpdatetxt.setText("Update Email");
                emailUpdatetxt.setBorder(defaultBorder);
            } 
    }//GEN-LAST:event_emailUpdatetxtFocusLost

    private void saveUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUpdateBtnActionPerformed
        String name = nameUpdatetxt.getText();
        String phoneNumber = phoneNumberUpdatetxt.getText();
        String email = emailUpdatetxt.getText();
        
        passengerManager.updatePassenger(this.passenger.getPassengerID(), name, email, phoneNumber);
        passengerManager.savePassengersToCSV();
        passengerDashboard.updateWelcomelbl();
        this.dispose();
    }//GEN-LAST:event_saveUpdateBtnActionPerformed

    private void deleteAccountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountBtn1ActionPerformed
        this.passengerManager.deletePassenger(this.passenger.getPassengerID());
        this.passengerManager.savePassengersToCSV();
    }//GEN-LAST:event_deleteAccountBtn1ActionPerformed

    private void addHoverEffect(final JButton button, final Color normal, final Color hover) {
    button.setOpaque(true);
    button.setBackground(normal);
    button.setBorderPainted(false);

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hover);
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normal);
        }
    });
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteAccountBtn1;
    private javax.swing.JTextField emailUpdatetxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameUpdatetxt;
    private javax.swing.JTextField phoneNumberUpdatetxt;
    private javax.swing.JButton saveUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
