/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Owner
 */
public class UpdatePassengerProfileGUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePassengerProfileGUI
     */
    public UpdatePassengerProfileGUI() {
        initComponents();
        setAutoRequestFocus(false);
        setLocationRelativeTo(null);
        addHoverEffect(deleteAccountBtn1, Color.WHITE, Color.GREEN);
        addHoverEffect(saveUpdateBtn, Color.WHITE, Color.GREEN);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameUpdatetxt = new javax.swing.JTextField();
        phoneNumberUpdatetxt = new javax.swing.JTextField();
        emailUpdatetxt = new javax.swing.JTextField();
        saveUpdateBtn = new javax.swing.JButton();
        deleteAccountBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 224, 223));

        nameUpdatetxt.setForeground(new java.awt.Color(153, 153, 153));
        nameUpdatetxt.setText("Update Name");
        nameUpdatetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameUpdatetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameUpdatetxtFocusLost(evt);
            }
        });
        nameUpdatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUpdatetxtActionPerformed(evt);
            }
        });

        phoneNumberUpdatetxt.setForeground(new java.awt.Color(153, 153, 153));
        phoneNumberUpdatetxt.setText("Update Phone Number");
        phoneNumberUpdatetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberUpdatetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumberUpdatetxtFocusLost(evt);
            }
        });
        phoneNumberUpdatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberUpdatetxtActionPerformed(evt);
            }
        });

        emailUpdatetxt.setForeground(new java.awt.Color(153, 153, 153));
        emailUpdatetxt.setText("Update Email");
        emailUpdatetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailUpdatetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailUpdatetxtFocusLost(evt);
            }
        });

        saveUpdateBtn.setBackground(new java.awt.Color(89, 167, 65));
        saveUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveUpdateBtn.setText("Save Update");

        deleteAccountBtn1.setBackground(new java.awt.Color(89, 167, 65));
        deleteAccountBtn1.setForeground(new java.awt.Color(255, 255, 255));
        deleteAccountBtn1.setText("Delete Account");
        deleteAccountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAccountBtn1))
                    .addComponent(emailUpdatetxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameUpdatetxt)
                    .addComponent(phoneNumberUpdatetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(nameUpdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneNumberUpdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailUpdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveUpdateBtn)
                    .addComponent(deleteAccountBtn1))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumberUpdatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberUpdatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberUpdatetxtActionPerformed

    private void nameUpdatetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameUpdatetxtFocusGained
        if (nameUpdatetxt.getText().equals("Update Name")) {
                nameUpdatetxt.setText("");
                nameUpdatetxt.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
            }       
    }//GEN-LAST:event_nameUpdatetxtFocusGained

    private void nameUpdatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUpdatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameUpdatetxtActionPerformed

    private void nameUpdatetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameUpdatetxtFocusLost
        if (nameUpdatetxt.getText().isEmpty()) {
                nameUpdatetxt.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                nameUpdatetxt.setText("Update Name");
            } 
    }//GEN-LAST:event_nameUpdatetxtFocusLost

    private void phoneNumberUpdatetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberUpdatetxtFocusGained
        if (phoneNumberUpdatetxt.getText().equals("Update Phone Number")) {
                phoneNumberUpdatetxt.setText("");
                phoneNumberUpdatetxt.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
            }   
    }//GEN-LAST:event_phoneNumberUpdatetxtFocusGained

    private void phoneNumberUpdatetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberUpdatetxtFocusLost
        if (phoneNumberUpdatetxt.getText().isEmpty()) {
                phoneNumberUpdatetxt.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                phoneNumberUpdatetxt.setText("Update Phone Number");
            } 
    }//GEN-LAST:event_phoneNumberUpdatetxtFocusLost

    private void emailUpdatetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUpdatetxtFocusGained
        if (emailUpdatetxt.getText().equals("Update Email")) {
                emailUpdatetxt.setText("");
                emailUpdatetxt.setForeground(new java.awt.Color(0, 0, 0)); // Typing color
            }
    }//GEN-LAST:event_emailUpdatetxtFocusGained

    private void emailUpdatetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUpdatetxtFocusLost
        if (emailUpdatetxt.getText().isEmpty()) {
                emailUpdatetxt.setForeground(new java.awt.Color(153, 153, 153)); // Placeholder color
                emailUpdatetxt.setText("Update Email");
            } 
    }//GEN-LAST:event_emailUpdatetxtFocusLost

    private void deleteAccountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAccountBtn1ActionPerformed

    private void addHoverEffect(final JButton button, final Color normal, final Color hover) {
    button.setOpaque(true);
    button.setBackground(normal);
    button.setBorderPainted(false);

    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hover);
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(normal);
        }
    });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengerProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengerProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengerProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengerProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePassengerProfileGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteAccountBtn1;
    private javax.swing.JTextField emailUpdatetxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameUpdatetxt;
    private javax.swing.JTextField phoneNumberUpdatetxt;
    private javax.swing.JButton saveUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
